Done the download thing with Winetricks. Now the Wine installing thing.

diff --git a/apt_install_winetricks b/apt_install_winetricks
--- a/apt_install_winetricks
+++ b/apt_install_winetricks
@@ -38,35 +38,39 @@ FOUND_PACKAGES=$(sudo apt-cache search --names-only winetricks)
 
 if [ "$FOUND_PACKAGES" == "" ];
 then
-    TMP_CONTRIB_SOURCES_LIST="/var/tmp/debian-contrib.sources"
-    CONTRIB_SOURCES_LIST="/etc/apt/sources.list.d/debian-contrib.sources"
+    "$SCRIPT_DIR/prepare_apt"
 
-    echo "Types: deb" > $TMP_CONTRIB_SOURCES_LIST
-    echo "URIs: http://deb.debian.org/debian" >> $TMP_CONTRIB_SOURCES_LIST
-    echo "Suites: bookworm bookworm-updates" >> $TMP_CONTRIB_SOURCES_LIST
-    echo "Components: contrib" >> $TMP_CONTRIB_SOURCES_LIST
+    # TMP_CONTRIB_SOURCES_LIST="/var/tmp/debian-contrib.sources"
+    # CONTRIB_SOURCES_LIST="/etc/apt/sources.list.d/debian-contrib.sources"
+
+    # echo "Types: deb" > $TMP_CONTRIB_SOURCES_LIST
+    # echo "URIs: http://deb.debian.org/debian" >> $TMP_CONTRIB_SOURCES_LIST
+    # echo "Suites: bookworm bookworm-updates" >> $TMP_CONTRIB_SOURCES_LIST
+    # echo "Components: contrib" >> $TMP_CONTRIB_SOURCES_LIST
     
-    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" \
-            >> $TMP_CONTRIB_SOURCES_LIST
+    # echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" \
+    #         >> $TMP_CONTRIB_SOURCES_LIST
 
-    sudo mv "${TMP_CONTRIB_SOURCES_LIST}" "${CONTRIB_SOURCES_LIST}"
+    # sudo mv "${TMP_CONTRIB_SOURCES_LIST}" "${CONTRIB_SOURCES_LIST}"
 
-    if ! [ "$?" == "0" ];
-    then
-        abort "Failed enabling 'contrib' packages."
-    fi
+    # if ! [ "$?" == "0" ];
+    # then
+    #     abort "Failed enabling 'contrib' packages."
+    # fi
 
-    echo "Enabled 'contrib' packages."
+    # echo "Enabled 'contrib' packages."
 
-    echo ""
-    echo "Refreshing APT database ..."
-    echo "---------------------------"
+    # echo ""
+    # echo "Refreshing APT database ..."
+    # echo "---------------------------"
 
-    sudo apt update 
+    # sudo apt update 
 fi
 
 
 echo ""
+echo "Installing Winetricks ..."
+echo "-------------------------"
 
 sudo apt install -y winetricks
 
diff --git a/prepare_apt b/prepare_apt
--- a/prepare_apt
+++ b/prepare_apt
@@ -15,12 +15,46 @@ function abort
 }
 
 
+function enable_debian_contrib
+{
+    TMP_SOURCES_LIST="/var/tmp/debian-contrib.sources"
+    SOURCES_LIST="/etc/apt/sources.list.d/debian-contrib.sources"
+    
+    DEB_VERSION=$DISTRO_VERSION_NAME
+
+    echo "Types: deb" > $TMP_SOURCES_LIST
+    echo "URIs: http://deb.debian.org/debian" >> $TMP_SOURCES_LIST
+    echo "Suites: ${DEB_VERSION} ${DEB_VERSION}-updates" >> $TMP_SOURCES_LIST
+    echo "Components: contrib" >> $TMP_SOURCES_LIST
+    
+    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" \
+            >> $TMP_SOURCES_LIST
+
+    sudo mv "${TMP_SOURCES_LIST}" "${SOURCES_LIST}"
+
+    if ! [ "$?" == "0" ];
+    then
+        abort "Failed enabling 'contrib' packages."
+    fi
+
+    sudo apt update
+
+    echo ""
+    echo "Enabled 'contrib' packages."
+    echo ""
+}
+
+
 SCRIPT_DIR=$(realpath $(dirname $0))
 
 
 
 
-DISTRO_VERSION_NAME=$("$SCRIPT_DIR/os_version_name")
+echo "Checking if APT is ready for downloading Wine and Winetricks..."
+echo ""
+
+
+export DISTRO_VERSION_NAME=$("$SCRIPT_DIR/os_version_name")
 
 source "$SCRIPT_DIR/get_wine_urls"
 
@@ -79,6 +113,42 @@ else
         echo ""
     fi
 fi
+
+
+if [ -f "/etc/apt/sources.list" ];
+then
+    cat /etc/apt/sources.list | grep contrib > /dev/null
+    CONTRIB_ENABLED=$?
+
+elif [ -f "/etc/apt/sources.list.d/debian.sources" ];
+then
+    cat /etc/apt/sources.list.d/debian.sources | grep contrib > /dev/null
+    CONTRIB_ENABLED=$?
+fi
+
+
+if ! [ "$CONTRIB_ENABLED" == "0" ];
+then
+    echo "Didn't found 'contrib' enabled in sources list. Trying to enable..."
+    echo ""
+
+    enable_debian_contrib
+fi
+
+
+echo "All seems ready for APT downloading."
+echo ""
+
+
+
+
+
+
+
+
+
+
+
 
 
 
