Added a check before installing dependencies for ARM systems. Let's try to create separate scripts for installing unpacked Wine.

diff --git a/install_wine32_for_arm b/install_wine32_for_arm
--- a/install_wine32_for_arm
+++ b/install_wine32_for_arm
@@ -19,7 +19,9 @@ function usage
 {
     echo "Usage: install_wine32_for_arm [branch] [version]"
     echo ""
-    echo "Branch: stable, staging or devel"
+    echo "Branch is one of stable, staging or devel."
+    echo "Default branch: staging"
+    echo "Default version: 9.3"
     echo ""
 }
 
@@ -78,14 +80,14 @@ then
     echo "because Box86-64 doesn't support newer versions yet."
     echo ""
 
-    USE_CACHED_WINE=1
+    USE_CACHE=1
 fi
 
 
 "$SCRIPT_DIR/install_deps_for_armhf"
 
 
-if [ "$USE_CACHED_WINE" == "1" ] && [ "$IN_ANDROID" == "1" ];
+if [ "$IN_ANDROID" == "1" ];
 then
     WINE_BRANCH="staging"
     WINE_VERSION="9.3"  
@@ -94,50 +96,68 @@ else
     then
         WINE_BRANCH="staging"
 
-	echo "No branch specified. Using 'staging' by default."
-	echo ""
+        echo "No branch specified. Using 'staging' by default."
+	    echo ""
+    fi
+
+    if [ "$WINE_VERSION" == "" ];
+    then
+        WINE_VERSION="9.3"
+
+        echo "No version specified. Using 9.3 by default."
+        echo ""
     fi
 fi
 
 
-#echo ""
-#echo "Installing Wine ${WINE_BRANCH} ${WINE_VERSION} (${WINE_ARCH}) ..."
-#echo "-----------------------------------------------------------------"
+if ! ["$IN_ANDROID" == "1" ];
+then
+    source "$SCRIPT_DIR/check_site"
+
+    if ! [ "$WINE_URL_OK" == "1" ];
+    then
+        USE_CACHE=1
+
+        echo "Can't download Wine. Using cached version."
+        echo ""
+    fi
+fi
+
+
+echo ""
+echo "Installing Wine ${WINE_BRANCH} ${WINE_VERSION} (${WINE_ARCH}) ..."
+echo "-----------------------------------------------------------------"
 
 WINE_TMP="/var/tmp/wine-${WINE_VERSION}"
 
-if [ "$IN_ANDROID" == "1" ];
+if [ "$IN_ANDROID" == "1" ] || [ "$USE_CACHE" == "1" ];
 then
     PACKAGE_1="wine-${WINE_BRANCH}_${WINE_VERSION}"
     PACKAGE_1+="~bullseye-1_${WINE_ARCH}.deb"
 
     PACKAGE_2="wine-${WINE_BRANCH}-${WINE_ARCH}_${WINE_VERSION}"
     PACKAGE_2+="~bullseye-1_${WINE_ARCH}.deb"
-fi
 
-if ! [ "$USE_CACHED_WINE" == "1" ];
-then
-    "$SCRIPT_DIR/download_wine" $WINE_BRANCH $WINE_VERSION $WINE_ARCH
-fi
-
-
-# TODO: HAY QUE REVISAR Y LIMPIAR ESTO
-
-if [ "$IN_ANDROID" == "1" ] || [ "$USE_CACHED_WINE" == "1" ];
-then
-    sudo dpkg-deb -x "${CACHE}/${PACKAGE_1}" "${WINE_TMP}"
+    dpkg-deb -x "${CACHE}/${PACKAGE_1}" "${WINE_TMP}"
 
     if ! [ "$?" == "0" ];
     then
         abort "Failed extracting '${PACKAGE_1}'."
     fi
 
-
-    sudo dpkg-deb -x "${CACHE}/${PACKAGE_2}" "${WINE_TMP}"
+    dpkg-deb -x "${CACHE}/${PACKAGE_1}" "${WINE_TMP}"
 
     if ! [ "$?" == "0" ];
     then
         abort "Failed extracting '${PACKAGE_2}'."
+    fi
+
+else
+    "$SCRIPT_DIR/download_wine" $WINE_BRANCH $WINE_VERSION $WINE_ARCH
+
+    if ! [ -f "${WINE_TMP}/extract" ];
+    then
+        abort "Can't continue with the install."
     fi
 fi
 
