Reworking a bit the dependency installation thing.

diff --git a/cmds/install_wine b/cmds/install_wine
--- a/cmds/install_wine
+++ b/cmds/install_wine
@@ -213,6 +213,32 @@ then
 fi
 
 
+if [ "$ARCH" == "i386" ] || [ "$ARCH" == "both" ];
+then
+    if ! [ -f "$HOME/.wine32_deps_installed" ];
+    then
+        echo "Installing Wine32 dependencies. They may be installed yet, but"
+        echo "cannot find the ~/.wine32_deps_installed file."
+        echo ""
+
+        "$SCRIPT_DIR/install_deps"
+    fi
+fi
+
+
+if [ "$ARCH" == "amd64" ] || [ "$ARCH" == "both" ];
+then
+    if ! [ -f "$HOME/.wine64_deps_installed" ];
+    then
+        echo "Installing Wine64 dependencies. They may be installed yet, but"
+        echo "cannot find the ~/.wine64_deps_installed file."
+        echo ""
+
+        "$SCRIPT_DIR/install_deps"
+    fi
+fi
+
+
 echo ""
 echo "Downloading wine-${WINE_BRANCH} (${WINE_VERSION})..."
 echo "-----------------------------------------------------"
diff --git a/install_deps b/install_deps
--- a/install_deps
+++ b/install_deps
@@ -25,13 +25,20 @@ export PATH="$SCRIPT_DIR/aux":$PATH
 
 ARCH=$(packages_arch)
 OS_NAME=$(os_name)
-OS_VERSION_NAME=$(os_version_name)
+OS_VERSION=$(os_version_name)
 
 
-echo "Installing Wine dependencies for $OS_NAME ($OS_VERSION_NAME)."
+echo "Installing Wine dependencies for $OS_NAME ($OS_VERSION)."
 echo ""
 
 
-"$SCRIPT_DIR/install_deps_for_${ARCH}_${OS_VERSION_NAME}"
+DEPS_INSTALL_SCRIPT="$SCRIPT_DIR/install_deps_for_${ARCH}_${OS_VERSION}"
 
+if ! [ -f "$DEPS_INSTALL_SCRIPT" ];
+then
+    echo "This distro or version have not been tested."
+    abort "You can try running one of the install_deps scripts."
+else
+    "$DEPS_INSTALL_SCRIPT"
+fi
 
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -131,5 +131,25 @@ cp "$SCRIPT_DIR/.wine_env" "$HOME/.wine_env"
 echo "$WINE_ENV_PATH" > "$HOME/.wine-env_path"
 
 
-echo "Done."
+if ! [ -f "/etc/apt/keyrings/winehq-archive.key" ];
+then
+    echo "WineHQ key not found in keyring. Setting up APT..."
+    echo ""
+
+    "$SCRIPT_DIR/prepare_apt"
+fi
+
+
+if ! [ -f "$HOME/.wine32_deps_installed" ];
+then
+    echo "Installing Wine dependencies. They may be installed yet, but"
+    echo "cannot find the ~/.wine_deps_installed file."
+    echo ""
+
+    "$SCRIPT_DIR/install_deps"
+fi
+
+
+echo "Basic setup is done. Now is time to install a Wine version"
+echo "if you have not done it yet."
 echo ""
