Cleaning the win_start script.

diff --git a/cmds/win_start b/cmds/win_start
--- a/cmds/win_start
+++ b/cmds/win_start
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-
 abort()
 {
     MESSAGE=$1
@@ -15,84 +14,11 @@ abort()
 }
 
 
-# Checks if a Wine enviroment file exists in the current folder
-# and loads it. The file is named .wine_env.
-activate_app_env()
-{
-    if [ -f "$SCRIPT_PATH/.wine_env" ];
-    then
-        source "$SCRIPT_PATH/.wine_env"
-
-        if ! [ "$WINELOADER" == "" ] && ! [ "$WINEPREFIX" == "" ];
-        then
-            echo -n "Using wine-${WINE_BRANCH} (${WINE_VERSION})"
-            echo "with prefix '$WINEPREFIX'."
-            echo ""
-
-        else
-            abort "WINELOADER and WINEPREFIX are missing from .wine_env."
-            abort "Cannot launch anything."
-        fi
-
-    else
-        echo "Cannot check the Wine environment to use: .wine_env is missing."
-        echo "Will use the default one for the executable architecture."
-        echo ""
-
-        if ! [ -f "$HOME/.default_win32_env" ] && ! [ -f "$HOME/.default_win64_env" ];
-        then
-            echo "Cannot determine the default wine for use."
-            abort "~/.default_win32_env and ~/.default_win64_env are both missing."
-        fi
-
-        USE_DEFAULT_WINE=1
-    fi
-}
-
-
-# Loads the Wine environment associated to the given executable
-# if there is any.
-#
-# The file needs to be named {exec filename}.wine_env.
-# For example: UnrealTournament.wine_env
-#
-activate_exec_env()
-{
-    EXEC=$1
-
-    echo "Checking if a .wine_env for this executable exists..."
-
-    EXEC_FILENAME=$(basename "$EXEC" .exe)
-    ENV_FILE=$SCRIPT_PATH/$EXEC_FILENAME.wine_env
-
-    if [ -f "$ENV_FILE" ];
-    then
-        source "$ENV_FILE"
-
-        if ! [ "$WINE_VERSION" == "" ];
-        then
-            . use_wine /opt/wine-$WINE_VERSION-$WINE_ARCH
-
-        elif ! [ "$WINE_PATH" == "" ];
-        then
-            . use_wine "$WINE_PATH"
-        fi
-
-        if [ "$?" == "0" ];
-        then
-            echo "Using wine-${WINE_BRANCH} (${WINE_VERSION})"
-        else
-            abort "Failed loading Wine environment for '$EXEC'."
-        fi
-    fi
-}
-
-
 check_exec_arch()
 {
     EXEC_FILE=$1
 
-    echo "Checking if file '$EXEC_FILE' is a Windows executable..."    
+    echo "Checking if file '$EXEC_FILE' is a Windows executable..."
 
     FILE_TYPE=$(exec_type "$EXEC_FILE")
 
@@ -109,25 +35,9 @@ check_exec_arch()
 
         echo "Want to launch a Windows 64 bit executable."
         echo ""
+
     else
         abort "The given file isn't a Windows 32 or 64 bit executable."
-    fi
-}
-
-
-check_requirements()
-{
-    if ! [ -f "$HOME/.wine-setup_path" ];
-    then
-        abort "Wine-Setup seems to be missing."
-    fi
-
-
-    if ! [ -f "$HOME/.default_win32_env" ] && 
-       ! [ -f "$HOME/.default_win64_env" ];
-    then
-        echo "Default envs for Win32 and Win64 are missing."
-        abort "No Wine installation available?"
     fi
 }
 
@@ -141,7 +51,7 @@ usage()
 
 
 
-if [ "$1" == "-h" ] || [ "$1" == "--help" ];
+if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
 then
     usage
     abort
@@ -160,10 +70,12 @@ then
 fi
 
 
-source "$WINE_ENV_PATH/wine_cmds"
-
-
-check_requirements
+if ! [ -f "$HOME/.default_win32_env" ] &&
+   ! [ -f "$HOME/.default_win64_env" ];
+then
+    echo "Default envs for Win32 and Win64 are missing."
+    abort "No Wine installation available?"
+fi
 
 
 EXEC_PATH=$(realpath "$1")
@@ -171,9 +83,6 @@ ARGS="${@:2}"
 
 EXEC_DIR=$(dirname "$EXEC_PATH")
 EXEC_BASENAME=$(basename "$EXEC_PATH" .exe)
-
-
-check_exec_arch "$EXEC_PATH"
 
 
 if [ "$WINE32_NEEDED" == "0" ] && [ "$WINE64_NEEDED" == "" ];
@@ -189,8 +98,10 @@ EXEC_WINENV=$EXEC_DIR/$EXEC_BASENAME.winenv
 if ! [ -f "$EXEC_WINENV" ];
 then
     echo "No Wine environment associated with the executable was found."
+
 else
-    . "$EXEC_WINENV"
+    # If the executable has a Wine environment associated, load it
+    source "$EXEC_WINENV"
 
     EXEC_WINENV_LOADED=1
     echo "Loaded Wine environment '$EXEC_WINENV'."
@@ -199,71 +110,71 @@ fi
 
 if ! [ -f "$APP_WINENV" ];
 then
+    # If no Wine environment was loaded for the executable, check if
+    # the executable folder contains one and load it
     echo "No Wine environment associated with this app was found."
 
 else
-    . "$APP_WINENV"
+    source "$APP_WINENV"
 
     APP_WINENV_LOADED=1
     echo "Loaded Wine environment '$APP_WINENV'."
 fi
 
 
-if ! [ "$WINE_PATH" == "" ];
+if [ "$WINELOADER" == "" ];
 then
-    if [ -f "$WINE_PATH/.wine_version" ];
-    then
-        . wine_load "$WINE_PATH"
-    fi
+    # If no Wine environment has been loaded at this moment,
+    # try with the default one for the executable architecture
 
-elif ! [ "$WINE_BRANCH" == "" ] && ! [ "$WINE_VERSION" == "" ];
-then
+    check_exec_arch "$EXEC_PATH"
+
     if [ "$WINE32_NEEDED" == "1" ];
     then
-        if [ -d "/opt/wine-${WINE_VERSION}_i386/opt/wine-${WINE_BRANCH}" ];
+        if ! [ -f "$HOME/.default_win32_env" ];
         then
-            . wine_load /opt/wine-${WINE_VERSION}
+            abort "Cannot find ~/.default_win32_env. Install a win32 prefix."
         fi
+
+        source wine_load $(cat "$HOME/.default_win32_env")
 
     elif [ "$WINE64_NEEDED" == "1" ];
     then
-        if [ -d "/opt/wine-${WINE_VERSION}_amd64/opt/wine-${WINE_BRANCH}" ];
+        if ! [ -f "$HOME/.default_win64_env" ];
         then
-            . wine_load /opt/wine-${WINE_VERSION}
+            abort "Cannot find ~/.default_win64_env. Install a win64 prefix."
         fi
+
+        source wine_load $(cat "$HOME/.default_win64_env")
     fi
 
-else
-    echo "Using the default Wine for the executable architecture."
-    echo ""
-
-    if [ "$WINE32_NEEDED" == "1" ];
+    if [ "$WINELOADER" == "" ];
     then
-        if ! [ "$HOME/.default_win32_env" ];
-        then
-            echo "Cannot find ~/.default_win32_env."
-            abort "Unable to determine the Wine installation to use."
-        else
-            . wine_load $(cat ~/.default_win32_env)
-        fi
+        echo -n "Failed loading the default Wine environment "
+        echo "for the needed architecture."
+
+        abort "Install the needed prefix and set it the default one."
     fi
 fi
 
 
 if [ "$WINEPREFIX" == "" ];
 then
+    # If no Wine prefix has been loaded at this moment, activate
+    # the default for the needed architecture
+
     if [ "$WINE32_NEEDED" == "1" ] && [ -d "$HOME/.wine" ];
     then
-        . ~/.wine/activate
+        source ~/.wine/activate
 
     elif [ "$WINE64_NEEDED" == "1" ] && [ -d "$HOME/wine64" ];
     then
-        . ~/.wine64/activate
+        source ~/.wine64/activate
     fi
 
     if [ "$WINEPREFIX" == "" ];
     then
-        abort "Failed to load default Wine prefix."
+        abort "Failed to load the needed Wine prefix."
     fi
 fi
 
@@ -281,3 +192,4 @@ then
 
     wine "$EXEC_PATH" $ARGS
 fi
+
